/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-06-13 07:45:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class compose_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("		<style>\r\n");
      out.write("			.main{\r\n");
      out.write("				display: flex;\r\n");
      out.write("				width: 100vw;\r\n");
      out.write("			}\r\n");
      out.write("			.main-col-1{\r\n");
      out.write("				display: inline-block;\r\n");
      out.write("				width: 40%;\r\n");
      out.write("			}\r\n");
      out.write("			.main-col-2{\r\n");
      out.write("				display: inline-block;\r\n");
      out.write("				width: 60%;\r\n");
      out.write("				margin-left: 5vw;\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			.btn-send{\r\n");
      out.write("				background-color: transparent;\r\n");
      out.write("				border:  solid green;\r\n");
      out.write("				border-radius: 8px;\r\n");
      out.write("				height: 35px;\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("			.btn-send:hover{\r\n");
      out.write("				background-color: green;\r\n");
      out.write("				color: white;\r\n");
      out.write("			}\r\n");
      out.write("			.cancel{\r\n");
      out.write("				background-color: transparent;\r\n");
      out.write("				color: red;\r\n");
      out.write("			}\r\n");
      out.write("			.cancel:hover{\r\n");
      out.write("				background-color: red;\r\n");
      out.write("				color: white;\r\n");
      out.write("			}\r\n");
      out.write("			.inputBox{\r\n");
      out.write("				width: 43vw;\r\n");
      out.write("				height: 40px;\r\n");
      out.write("				border: 1px solid;\r\n");
      out.write("				border-radius: 5px;\r\n");
      out.write("			}\r\n");
      out.write("		</style>\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("	<div class=\"main-col-1\">\r\n");
      out.write("		<h2>Welcome to Mailservices!</h2>\r\n");
      out.write("							<p>Here we are providing a free <b>Mail Service</b> for all the employees<br>\r\n");
      out.write("							you can now just login into your account and can send data to other<br> \r\n");
      out.write("							employees for free! Let's Get Started!\r\n");
      out.write("						</p>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"main-col-2\">\r\n");
      out.write("		<div>\r\n");
      out.write("			");
 
			
		if(session.getAttribute("username")!=null){
		String username=(String)session.getAttribute("username");		
		out.print("<font style='color:navy'>Welcome "+username+"</font>");
		}
		else{
		request.setAttribute("Error1","Plz Do login First");
		
      out.write("\r\n");
      out.write("		");
      if (true) {
        _jspx_page_context.forward("index.jsp");
        return;
      }
      out.write("\r\n");
      out.write("			");
}
		
      out.write("\r\n");
      out.write("		");
 
		if(request.getAttribute("compose")!=null){
		String compose= (String)request.getAttribute("compose");
		out.print("<font style='color:navy'>"+compose+"</font>");
		}
		if(request.getAttribute("composeerr")!=null){
		String composeerr= (String)request.getAttribute("composeerr");
		out.print("<font style='color:navy'>"+composeerr+"</font>");
		}
		
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<h4>Compose Message</h4> <form action=\"composeEmail\" >\r\n");
      out.write("			<table>\r\n");
      out.write("	<tr><td>From : <input type=\"text\" style=\"border: none;\" name=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly/><br/></td></tr>\r\n");
      out.write("	 <tr><td>To&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: <input type=\"text\" name=\"reciever_id\"/><br/></td></tr>\r\n");
      out.write("	 <tr><td>Subject:<br/></td></tr>\r\n");
      out.write("	 <tr><td><input type=\"text\" name=\"subject\" class=\"inputBox\"></td></tr>\r\n");
      out.write("	 <tr><td>Message:<br/></td></tr>\r\n");
      out.write("	 \r\n");
      out.write("	 <tr><td><textarea rows=\"10\" cols=\"80\" name=\"message\"></textarea><br/></td></tr>\r\n");
      out.write("	 <tr><td><input class=\"btn-send\"type=\"submit\" value=\"Send\"/>&nbsp;&nbsp;&nbsp;<a class=\"cancel\" href=\"home.jsp\">cancel</a></td></tr>\r\n");
      out.write("	 \r\n");
      out.write("	 </table></form>\r\n");
      out.write("						\r\n");
      out.write("										\r\n");
      out.write("	</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
