/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-06-13 07:30:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Spidey/Documents/workspace-spring-tool-suite-4-4.5.1.RELEASE/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/mailcasting/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1623568916549L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \n");
      out.write("<!DOCTYPE HTML>\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("	<head>\n");
      out.write("		<title>Mail Services</title>\n");
      out.write("		<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("		<meta name=\"description\" content=\"\" />\n");
      out.write("		<meta name=\"keywords\" content=\"\" />\n");
      out.write("		<style>\n");
      out.write("			.title-container{\n");
      out.write("				background-color: #f8f9fa65!important;\n");
      out.write("				height: 130px;\n");
      out.write("				\n");
      out.write("			}\n");
      out.write("			.title{\n");
      out.write("				\n");
      out.write("			    text-align: center;\n");
      out.write("				border: 5px solid #f8f9fa!important;\n");
      out.write("				background-color:  #f8f9faf5!important;\n");
      out.write("				border-radius: 3px;\n");
      out.write("			}\n");
      out.write("			.main{\n");
      out.write("				display: flex;\n");
      out.write("				width: 100vw;\n");
      out.write("			}\n");
      out.write("			.main-col-1{\n");
      out.write("				display: inline-block;\n");
      out.write("				width: 40%;\n");
      out.write("			}\n");
      out.write("			.main-col-2{\n");
      out.write("				display: inline-block;\n");
      out.write("				width: 60%;\n");
      out.write("				margin-left: 5vw;\n");
      out.write("				\n");
      out.write("			}\n");
      out.write("			.inputBox{\n");
      out.write("				width: 25vw;\n");
      out.write("				height: 30px;\n");
      out.write("				border-radius: 5px;\n");
      out.write("			}\n");
      out.write("			.btn-login{\n");
      out.write("				background-color: transparent;\n");
      out.write("				border:  solid green;\n");
      out.write("				border-radius: 8px;\n");
      out.write("				height: 35px;\n");
      out.write("				\n");
      out.write("			}\n");
      out.write("			.btn-login:hover{\n");
      out.write("				background-color: green;\n");
      out.write("				color: white;\n");
      out.write("			}\n");
      out.write("			.btn-signin{\n");
      out.write("				background-color: transparent;\n");
      out.write("				border:blue;\n");
      out.write("				height: 35px;\n");
      out.write("			}\n");
      out.write("			.btn-signin:hover{\n");
      out.write("				background-color: blue;\n");
      out.write("				color: white;\n");
      out.write("			}\n");
      out.write("		</style>\n");
      out.write("	</head>\n");
      out.write("	<body>\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("	 \n");
      out.write("		\n");
      out.write("		\n");
      out.write("		<div class=\"title-container\">\n");
      out.write("			<br/>\n");
      out.write("			<div class=\"title\">\n");
      out.write("				<h1><a href=\"#\">Mail Casting Service</a></h1>							\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<br/>\n");
      out.write("\n");
      out.write("		<div class=\"main\">\n");
      out.write("			\n");
      out.write("		\n");
      out.write("					<div class=\"main-col-1\">\n");
      out.write("							<h2>Welcome to Mailservices!</h2>\n");
      out.write("							<p>Here we are providing a free <b>Mail Service</b> for all the employees<br>\n");
      out.write("							you can now just login into your account and can send data to other<br> \n");
      out.write("							employees for free! Let's Get Started!\n");
      out.write("						</p>\n");
      out.write("							\n");
      out.write("						</div>\n");
      out.write("						<div class=\"main-col-2\">\n");
      out.write("										<h3 style=\"color:#007897;\"> Login or Signup</h3><br>\n");
      out.write("										<div>\n");
      out.write("											\n");
      out.write("											");
 
										if(request.getAttribute("Error")!=null){
										String Error=(String)request.getAttribute("Error");
										out.print("<font style='color:red'>"+Error+"</font>");
										}
										
										if(request.getAttribute("Error1")!=null){
										System.out.print(request.getAttribute("Error1"));
										String Error1=(String)request.getAttribute("Error1");
										out.print("<font style='color:red'>"+Error1+"</font>");
										
										
										}
										if(request.getAttribute("register")!=null){
										System.out.print(request.getAttribute("register"));
										String register=(String)request.getAttribute("register");
										out.print("<font style='color:navy'>"+register+"</font>");
										}
										if(request.getAttribute("logout")!=null){
										System.out.print(request.getAttribute("logout"));
										String logout=(String)request.getAttribute("logout");
										out.print("<font style='color:navy'>"+logout+"</font>");
										} 
										
										
										
      out.write("\n");
      out.write("										\n");
      out.write("										\n");
      out.write("				<form action=\"login\" method=\"post\">\n");
      out.write("			\n");
      out.write("						<table style=\"table-layout: fixed\">\n");
      out.write("\n");
      out.write("									<tr>\n");
      out.write("										<td>Email id :</td>\n");
      out.write("									</tr>\n");
      out.write("										<tr>\n");
      out.write("										<td> <input class=\"inputBox\"  type=\"text\"  name=\"email\"><br></td>\n");
      out.write("										</tr>\n");
      out.write("			\n");
      out.write("									<tr><td>Password:</td></tr>\n");
      out.write("									<tr><td> <input class=\"inputBox\" type=\"password\" name=\"password\"><br></td></tr>\n");
      out.write("				\n");
      out.write("									<tr><td><br><input class=\"btn-login\" type=\"submit\" value=\"Sign in\">&nbsp; &nbsp; &nbsp;  &nbsp;  &nbsp; \n");
      out.write("										 <a href=\"Register.jsp\" class=\"btn-signin\">Don't have an account?</a> </td></tr>\n");
      out.write("						</table>\n");
      out.write("				</form>\n");
      out.write("\n");
      out.write("						</div>\n");
      out.write("						\n");
      out.write("						</div>\n");
      out.write("				</div>\n");
      out.write("		\n");
      out.write("			</body>\n");
      out.write("\n");
      out.write("	\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
